export const RoutesEnum = {
  HOME: "/swap-it-up-front/",
  CHATS: "/swap-it-up-front/chats",
  ADD_ITEM: "/swap-it-up-front/add",
  EDIT_ITEM: "/swap-it-up-front/edit/:id",
  MY_DEALS: "/swap-it-up-front/my-deals",
  MY_ITEMS: "/swap-it-up-front/my-items",
  ITEM: "/swap-it-up-front/item/:id",
  SIGN_IN: "/swap-it-up-front/sign-in",
  SIGN_UP: "/swap-it-up-front/sign-up",
  SETTINGS: "/swap-it-up-front/settings",
  PROFILE: "/swap-it-up-front/profile/:id",
  ADMIN: "/swap-it-up-front/admin",
  NOT_FOUND: "/swap-it-up-front/404",
};
